import { loadPosts } from "@/utils/blog.ts";
import * as path from "$std/path/mod.ts";

// Generate a single file to import all blog posts from
const { posts, images } = await loadPosts();

const postsCache = path.join(Deno.cwd(), "posts.gen.ts");
const postsImport = [...posts.entries()].map(([slug, p]) =>
  `blogPosts.set("${slug}", ${JSON.stringify(p)});`
).join("\n");
const imagesImport = [...images.entries()].map(([key, value]) =>
  `blogImages.set("${key}", "${value}");`
).join("\n");
const content = `// DO NOT EDIT. This file is autogenerated.

import { BlogPost } from "@/utils/blog.ts";

export const blogPosts: Map<string, BlogPost> = new Map();
export const blogImages: Map<string, string> = new Map();

${postsImport}

${imagesImport}
`;
await Deno.writeTextFile(postsCache, content);
