// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/img.ts";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/js/stats-event.ts";
import * as $3 from "./routes/js/stats.js.ts";
import * as $4 from "./routes/post/[slug].tsx";
import * as $5 from "./routes/sitemap.xml.ts";
import * as $$0 from "./islands/BlogPostImports.tsx";

const manifest = {
  routes: {
    "./routes/img.ts": $0,
    "./routes/index.tsx": $1,
    "./routes/js/stats-event.ts": $2,
    "./routes/js/stats.js.ts": $3,
    "./routes/post/[slug].tsx": $4,
    "./routes/sitemap.xml.ts": $5,
  },
  islands: {
    "./islands/BlogPostImports.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
