# fly.toml app configuration file for zaynetro Phoenix app
app = 'zaynetro-com'
primary_region = 'ams'

[build]

[env]
  PORT = '4000'
  PHX_HOST = 'www.zaynetro.com'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = "off"
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/healthz"
    timeout = "5s"

[[vm]]
  memory = '1024mb'
  cpus = 1
  memory_mb = 1024
