name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  www:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Mock posts.gen.ts
        run: |
          mkdir -p build
          cp posts.gen.ts.empty build/posts.gen.ts

      - name: Check format
        run: deno fmt --check

      - name: Check linting
        run: deno lint

      - name: Typecheck main.ts
        run: deno check main.ts
